spring.application.name=hexagonal
client.address.url=http://localhost:8082/address

spring.cloud.config.enabled=false

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.authentication-database=admin
spring.mongodb.username=root
spring.mongodb.password=example
spring.mongodb.database=hexagonal-db
